from . import ohc
from . import project
from . import hr_employee
from . import maintenance_equipment
from . import ambulance
from . import res_partner
from . import crm_lead
from . import survey
from . import survey_wizard
from . import helpdesk